import localFont from "next/font/local"
import "./globals.css";

const comicFont = localFont({
  src: 'comic.ttf'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={comicFont.className}>{children}</body>
    </html>
  );
}
